server {
    listen 8080;
    server_name _;
    root /var/www/html/public;
    index index.php;

    include /etc/nginx/snippets/tus-public.location.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 8 16k;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_pass app:9000;
        fastcgi_read_timeout 300s;
    }

    location ~ /\. {
        deny all;
    }
}
